eureka:
  client:
    healthcheck:
      enabled: true #开启健康检查
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${DEV.HOST:localhost}:18761/eureka/

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DEV.HOST:localhost}:3306/framework?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
  redis:
    database: 0
    host: ${DEV.HOST:localhost}
    port: 6379
    password:
    timeout: 10000
    lettuce:
      pool:
        max-active: 300
        max-wait: -1ms
        max-idle: 80
        min-idle: 10

#swagger
swagger:
  enable: true
  basePackage: com.cloud
  groupName: 认证服务文档
  defaultLogin: false

#打印sql
DEBUG: true
logging:
  level:
    root: INFO
    com:
      cloud: DEBUG