eureka:
  client:
    healthcheck:
      enabled: true #开启健康检查
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${DEV.HOST:localhost}:8761/eureka/

#打印sql
DEBUG: true
logging:
  level:
    root: INFO
    com:
      cloud: DEBUG